name: Develop Flow

# Trigger this workflow manually with the workflow_dispatch event
on:
  workflow_dispatch:
    inputs:
      destination:
        description: 'Destination'
        required: true
        type: string

run-name: Deploy to Develop Databricks at destination ${{ inputs.destination }} by @${{ github.actor }}

# env:
#   # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DEV }}
#   # AZURE_SP_APPLICATION_ID: ${{ secrets.ARM_CLIENT_ID }}
#   # AZURE_SP_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#   # AZURE_SP_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
#   DATABRICKS_BUNDLE_ENV: develop

jobs:
  validate_deploy:
    runs-on: ubuntu-latest
    environment:
      name: develop
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Prepare Databricks CLI 
        uses: databricks/setup-cli@main
      - name: Set Version
        run: |
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # - name: Log in azure
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ env.AZURE_CREDENTIALS }}
      - name: connect databricks
          env:
            DATABRICKS_HOST: https://adb-3590073163084620.0.azuredatabricks.net/
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          run: |
            databricks configure
      - name: Run Databricks bundle validate 
        working-directory: ./${{ inputs.destination }}
        run: |
          databricks bundle validate --var release=${{ env.VERSION }} -t develop
      - name: Run Databricks bundle deploy 
        working-directory: ./${{ inputs.destination }}
        run: |
          databricks bundle deploy --var release=${{ env.VERSION }} -t develop