---
name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # linters:
  #   if: github.event.pull_request.draft == false
  #   uses: yaperos/reusable-workflows/.github/workflows/linters.yaml@main
  #   with:
  #     node_version: 18.18.0
  #     lint_command: npm run lint
  #   secrets: inherit
  generate_coverage:
    name: Generate Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    #para coverage python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox and any other packages
      run: pip install tox
    - name: Run tox
      working-directory: ./
      run: tox -e py,lint,ruff
    # Para coverage scala
    - name: Validate execution scala
      run: |
        VALUE=$(cat execute_test_scala)
        echo "EXECUTE_TEST_ESCALA=$VALUE" >> $GITHUB_ENV

    - name: Run tests Scala
      if: env.EXECUTE_TEST_ESCALA == 'true'
      run: |
        sbt clean coverage test
        sbt coverageAggregate
    #Corrigiendo bug de sonar path en scoverage.xml
    - name: Replace all working directory paths with sources path
      run: |
        if [[ -f "target/scala-2.12/scoverage-report/scoverage.xml" ]]; then sed -i -e s,`pwd`,/github/workspace,g target/scala-2.12/scoverage-report/scoverage.xml; fi
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: unit_test_coverage
        path: |
          coverage.xml
          target/scala-2.12/scoverage-report/scoverage.xml
          pytest.ini

  code_scanner:
    needs: generate_coverage
    uses: yaperos/reusable-workflows/.github/workflows/code_scanner.yaml@main
    with:
      environment: qa
      slack_channel: deploys
      report_coverage: true
      checkmarx_tenant: yape
      checkmarx_args: --threshold "sast-high=1;sca-high=1;kics-high=1" --report-format sarif --output-path .
    secrets: inherit
